#!/usr/bin/env python3
"""Generate the compact Unicode 17 sentence-property index from pinned Unicode data."""
import argparse
import hashlib
import re
from pathlib import Path
ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / 'tools/sentence-tests/data/SentenceBreakProperty-17.0.0.txt'
TARGET = ROOT / 'native/sentence/unicode_data.h'
CATEGORIES = ROOT / 'tools/sentence-tests/data/DerivedGeneralCategory-17.0.0.txt'

def generate():
    source = SOURCE.read_bytes()
    ranges = []
    ascii_props = ['Other'] * 128
    for line in source.decode().splitlines():
        line = line.split('#')[0].strip()
        if not line: continue
        points, prop = map(str.strip, line.split(';'))
        ends = points.split('..')
        lo, hi = int(ends[0],16), int(ends[-1],16)
        for point in range(lo, min(hi,127)+1): ascii_props[point]=prop
        if hi >= 128: ranges.append((max(128,lo),hi,prop))
    ranges.sort()
    merged=[]
    for lo,hi,prop in ranges:
        if merged and merged[-1][1]+1==lo and merged[-1][2]==prop:
            merged[-1]=(merged[-1][0],hi,prop)
        else: merged.append((lo,hi,prop))
    lines=['// Generated by tools/sentence-tests/generate_unicode.py; do not edit.',
           '// Unicode 17.0.0 data: Unicode-3.0 license; see licenses/Unicode-3.0.txt.',
           '// SentenceBreakProperty SHA-256: '+hashlib.sha256(source).hexdigest(),
           '// DerivedGeneralCategory SHA-256: '+hashlib.sha256(CATEGORIES.read_bytes()).hexdigest(), '#pragma once',
           'namespace foxlet::sentence {',
           'enum class Property : unsigned char { Other, CR, LF, Extend, Sep, Format, Sp, Lower, Upper, OLetter, Numeric, ATerm, STerm, Close, SContinue };',
           'inline constexpr Property asciiProperties[] = {']
    for i in range(0,128,8): lines.append('  '+', '.join('Property::'+x for x in ascii_props[i:i+8])+',')
    lines += ['};','struct PropertyRange { char32_t first, last; Property property; };','inline constexpr PropertyRange propertyRanges[] = {']
    lines += [f'  {{0x{lo:X}, 0x{hi:X}, Property::{prop}}},' for lo,hi,prop in merged]
    lines += ['};','struct OpeningRange { char32_t first, last; };', 'inline constexpr OpeningRange openingRanges[] = {']
    categories = CATEGORIES.read_text()
    openings = []
    for line in categories.splitlines():
        line = line.split('#')[0].strip()
        if not line: continue
        points, category = map(str.strip, line.split(';'))
        if category not in ('Ps', 'Pi'): continue
        parts = points.split('..')
        openings.append((int(parts[0],16), int(parts[-1],16)))
    lines += [f'  {{0x{lo:X}, 0x{hi:X}}},' for lo,hi in sorted(openings)]
    lines += ['};','} // namespace foxlet::sentence','']
    return '\n'.join(lines)

if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    native = (ROOT / 'native/sentence/rules.h').read_text()
    kotlin = (ROOT / 'foxlet/src/main/kotlin/io/github/yinvoker/foxlet/PrefixTables.kt').read_text()
    expected = set(re.findall(r'\{"([a-z]+)",', native))
    actual = set(re.findall(r'"([a-z]+)"', re.search(r'setOf\((.*?)\)', kotlin).group(1)))
    declared = set(re.findall(r'"([a-z]+)"', re.search(r'ruleLanguages\[\] = \{(.*?)\}', native).group(1)))
    aliases = set(re.findall(r'\{"([a-z]+)",', re.search(r'ruleAliases\[\] = (.*?);', native).group(1)))
    if expected != actual or expected != declared | aliases: raise SystemExit('Kotlin prefix capabilities differ from native rule languages')
    data=generate()
    if args.check:
        if TARGET.read_text()!=data: raise SystemExit('Unicode index differs from pinned data')
    else: TARGET.write_text(data)
